apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-phpbb
 namespace: standard
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: phpbb
 minReplicas: 3
 maxReplicas: 6
 targetCPUUtilizationPercentage: 70
