apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:12.0-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: storedb
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: password
