nameSpace : helm
postgresName: postgresql
fastapiName: fastapi-deployment
pgadminName: pgadmin

configmap:
  name: my-configmap
  data:
    value: "trust"
    email: "admin@admin.com"


secret:
  name: my-secret
  type: Opaque
  data:
    user: YWRtaW4=
    db: c3RvcmVkYg==
    pwd: cGFzc3dvcmQ=
    pgadminpwd: cm9vdA==
    

imageFastApi:
  name: jobmounchili/fastapi
  tag: latest

imagePostgres:
  name: postgres
  tag: 12.0-alpine

imagePgadmin:
  name: dpage/pgadmin4

hpa:
  name: hpa-phpbb
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70