nameSpace : helm
postgresName: postgresql
fastapiName: fastapi-deployment
pgadminName: pgadmin

configmap:
  name: my-configmap
  data:
    user: "admin"
    db: "storedb"
    pwd: "password"
    value: "trust"


secret:
  name: my-secret
  type: Opaque
  data:
    user: YWRtaW4=
    db: c3RvcmVkYg==
    pwd: cGFzc3dvcmQ=
    

imageFastApi:
  name: jobmounchili/fastapi
  tag: latest

imagePostgres:
  name: postgres
  tag: 12.0-alpine

imagePgadmin:
  name: dpage/pgadmin4